### ISSUE TITLE
Boltz unable to receive str objects 

### ISSUE THREAD

**Issue by greenrace666** [modal-labs/modal-examples#1015]
I'm trying to run https://github.com/modal-labs/modal-examples/blob/main/06_gpu_and_ml/protein-folding/boltz1.py
and 

  0%|          | 0/1 [00:00<?, ?it/s]  0%|          | 0/1 [00:00<?, ?it/s]
Traceback (most recent call last):
    sys.exit(cli())
             ^^^^^
  File "/usr/local/lib/python3.12/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/boltz/main.py", line 566, in predict
    process_inputs(
  File "/usr/local/lib/python3.12/site-packages/lightning_utilities/core/rank_zero.py", line 42, in wrapped_fn
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/boltz/main.py", line 293, in process_inputs
    target = parse_yaml(path, ccd)
             ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/boltz/data/parse/yaml.py", line 57, in parse_yaml
    return parse_boltz_schema(name, data, ccd)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/boltz/data/parse/schema.py", line 509, in parse_boltz_schema
    version = schema.get("version", 1)
              ^^^^^^^^^^
AttributeError: 'str' object has no attribute 'get'

Can anyone help?

**Comment by charlesfrye** [comment]
Hmm what yaml file are you running on? Is it different from the one provided in the repo?

**Comment by greenrace666** [comment]
> Hmm what yaml file are you running on? Is it different from the one provided in the repo?

no , it's using the one in data folder

**Comment by charlesfrye** [comment]
Hmm, I am not able to replicate this issue. The problem is coming from the `boltz` library's code that parses the input yaml file. I don't see how it could end up passing a string instead of a dictionary. Seems like a bug on their end.

I am running the command given in the example:
```shell
modal run boltz1.py
```

Are you running that exact command, or something else?

**Comment by greenrace666** [comment]
Yes,the same

**Comment by greenrace666** [comment]
I've made a PR #1016 for fixes @charlesfrye
