### ISSUE TITLE
modal token new - error

### ISSUE THREAD

**Issue by magick93** [modal-labs/modal-examples#342]
Hello

Apologies if this is not the correct repo to post such an issue. 

When I run `modal token new` I get the following error:

```
Traceback (most recent call last):
  File "/home/anton/git/developer/.venv/bin/modal", line 5, in <module>
    from modal.__main__ import main
  File "/home/anton/git/developer/.venv/lib/pypy3.9/site-packages/modal/__init__.py", line 6, in <module>
    from .dict import Dict
  File "/home/anton/git/developer/.venv/lib/pypy3.9/site-packages/modal/dict.py", line 9, in <module>
    from ._serialization import deserialize, serialize
  File "/home/anton/git/developer/.venv/lib/pypy3.9/site-packages/modal/_serialization.py", line 6, in <module>
    import cloudpickle
  File "/home/anton/git/developer/.venv/lib/pypy3.9/site-packages/cloudpickle/__init__.py", line 4, in <module>
    from cloudpickle.cloudpickle import *  # noqa
  File "/home/anton/git/developer/.venv/lib/pypy3.9/site-packages/cloudpickle/cloudpickle.py", line 57, in <module>
    from .compat import pickle
  File "/home/anton/git/developer/.venv/lib/pypy3.9/site-packages/cloudpickle/compat.py", line 13, in <module>
    from _pickle import Pickler  # noqa: F401
ModuleNotFoundError: No module named '_pickle'
```

I am using the following python version:

```
Python 3.9.16 (feeb267ead3e6771d3f2f49b83e1894839f64fb7, Dec 29 2022, 14:23:21)
```

**Comment by luiscape** [comment]
Hi @magick93, this question was just responded in our internal Slack.

The issue here is the use of [PyPy](https://www.pypy.org/). We don't support PyPy at the moment as it seems to have a number of issues with our dependencies, including this issue with [cloudpickle](https://github.com/cloudpipe/cloudpickle/issues/455).
