### ISSUE TITLE
mixtral example

### ISSUE THREAD

**Issue by haiderasad** [modal-labs/modal-examples#527]
i think the mixtral tgi example is broken 
`
2023-12-20T12:33:48.503017Z  INFO text_generation_launcher: Files are already present on the host. Skipping download.

2023-12-20T12:33:49.729338Z  INFO download: text_generation_launcher: Successfully downloaded weights.
2023-12-20T12:33:49.731995Z  INFO shard-manager: text_generation_launcher: Starting shard rank=0
2023-12-20T12:33:49.732105Z  INFO shard-manager: text_generation_launcher: Starting shard rank=1
2023-12-20T12:33:49.750997Z  INFO shard-manager: text_generation_launcher: Starting shard rank=2
2023-12-20T12:33:49.751712Z  INFO shard-manager: text_generation_launcher: Starting shard rank=3
2023-12-20T12:33:59.806288Z  INFO shard-manager: text_generation_launcher: Waiting for shard to be ready... rank=1
2023-12-20T12:33:59.806311Z  INFO shard-manager: text_generation_launcher: Waiting for shard to be ready... rank=2
2023-12-20T12:33:59.806288Z  INFO shard-manager: text_generation_launcher: Waiting for shard to be ready... rank=0
2023-12-20T12:33:59.806325Z  INFO shard-manager: text_generation_launcher: Waiting for shard to be ready... rank=3
2023-12-20T12:34:08.721881Z  WARN text_generation_launcher: Disabling exllama v2 and using v1 instead because there are issues when sharding

2023-12-20T12:34:08.721948Z  WARN text_generation_launcher: Disabling exllama v2 and using v1 instead because there are issues when sharding

2023-12-20T12:34:08.721884Z  WARN text_generation_launcher: Disabling exllama v2 and using v1 instead because there are issues when sharding

2023-12-20T12:34:08.722307Z  WARN text_generation_launcher: Disabling exllama v2 and using v1 instead because there are issues when sharding

2023-12-20T12:34:09.822779Z  INFO shard-manager: text_generation_launcher: Waiting for shard to be ready... rank=0
2023-12-20T12:34:09.822815Z  INFO shard-manager: text_generation_launcher: Waiting for shard to be ready... rank=2
2023-12-20T12:34:09.898596Z  INFO shard-manager: text_generation_launcher: Waiting for shard to be ready... rank=1
2023-12-20T12:34:09.898623Z  INFO shard-manager: text_generation_launcher: Waiting for shard to be ready... rank=3
2023-12-20T12:34:18.485392Z ERROR text_generation_launcher: Error when initializing model
Traceback (most recent call last):
  File "/opt/conda/bin/text-generation-server", line 8, in <module>
    sys.exit(app())
  File "/opt/conda/lib/python3.10/site-packages/typer/main.py", line 311, in __call__
    return get_command(self)(*args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/typer/core.py", line 778, in main
    return _main(
  File "/opt/conda/lib/python3.10/site-packages/typer/core.py", line 216, in _main
    rv = self.invoke(ctx)
  File "/opt/conda/lib/python3.10/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/opt/conda/lib/python3.10/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/conda/lib/python3.10/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/typer/main.py", line 683, in wrapper
    return callback(**use_params)  # type: ignore
  File "/opt/conda/lib/python3.10/site-packages/text_generation_server/cli.py", line 89, in serve
    server.serve(
  File "/opt/conda/lib/python3.10/site-packages/text_generation_server/server.py", line 215, in serve
    asyncio.run(
  File "/opt/conda/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/opt/conda/lib/python3.10/asyncio/base_events.py", line 636, in run_until_complete
    self.run_forever()
  File "/opt/conda/lib/python3.10/asyncio/base_events.py", line 603, in run_forever
    self._run_once()
  File "/opt/conda/lib/python3.10/asyncio/base_events.py", line 1909, in _run_once
    handle._run()
  File "/opt/conda/lib/python3.10/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
> File "/opt/conda/lib/python3.10/site-packages/text_generation_server/server.py", line 161, in serve_inner
    model = get_model(
  File "/opt/conda/lib/python3.10/site-packages/text_generation_server/models/__init__.py", line 310, in get_model
    return FlashMixtral(
  File "/opt/conda/lib/python3.10/site-packages/text_generation_server/models/flash_mixtral.py", line 21, in __init__
    super(FlashMixtral, self).__init__(
  File "/opt/conda/lib/python3.10/site-packages/text_generation_server/models/flash_mistral.py", line 318, in __init__
    SLIDING_WINDOW_BLOCKS = math.ceil(config.sliding_window / BLOCK_SIZE)
TypeError: unsupported operand type(s) for /: 'NoneType' and 'int'

2023-12-20T12:34:18.498142Z ERROR text_generation_launcher: Error when initializing model
Traceback (most recent call last):
  File "/opt/conda/bin/text-generation-server", line 8, in <module>
    sys.exit(app())
  File "/opt/conda/lib/python3.10/site-packages/typer/main.py", line 311, in __call__
    return get_command(self)(*args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/typer/core.py", line 778, in main
    return _main(
  File "/opt/conda/lib/python3.10/site-packages/typer/core.py", line 216, in _main
    rv = self.invoke(ctx)
  File "/opt/conda/lib/python3.10/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/opt/conda/lib/python3.10/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/conda/lib/python3.10/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/typer/main.py", line 683, in wrapper
    return callback(**use_params)  # type: ignore
  File "/opt/conda/lib/python3.10/site-packages/text_generation_server/cli.py", line 89, in serve
    server.serve(
  File "/opt/conda/lib/python3.10/site-packages/text_generation_server/server.py", line 215, in serve
    asyncio.run(
  File "/opt/conda/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/opt/conda/lib/python3.10/asyncio/base_events.py", line 636, in run_until_complete
    self.run_forever()
  File "/opt/conda/lib/python3.10/asyncio/base_events.py", line 603, in run_forever
    self._run_once()
  File "/opt/conda/lib/python3.10/asyncio/base_events.py", line 1909, in _run_once
    handle._run()
  File "/opt/conda/lib/python3.10/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
> File "/opt/conda/lib/python3.10/site-packages/text_generation_server/server.py", line 161, in serve_inner
    model = get_model(
  File "/opt/conda/lib/python3.10/site-packages/text_generation_server/models/__init__.py", line 310, in get_model
    return FlashMixtral(
  File "/opt/conda/lib/python3.10/site-packages/text_generation_server/models/flash_mixtral.py", line 21, in __init__
    super(FlashMixtral, self).__init__(
  File "/opt/conda/lib/python3.10/site-packages/text_generation_server/models/flash_mistral.py", line 318, in __init__
    SLIDING_WINDOW_BLOCKS = math.ceil(config.sliding_window / BLOCK_SIZE)
TypeError: unsupported operand type(s) for /: 'NoneType' and 'int'

2023-12-20T12:34:18.510689Z ERROR text_generation_launcher: Error when initializing model
Traceback (most recent call last):
  File "/opt/conda/bin/text-generation-server", line 8, in <module>
    sys.exit(app())
  File "/opt/conda/lib/python3.10/site-packages/typer/main.py", line 311, in __call__
    return get_command(self)(*args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/typer/core.py", line 778, in main
    return _main(
  File "/opt/conda/lib/python3.10/site-packages/typer/core.py", line 216, in _main
    rv = self.invoke(ctx)
  File "/opt/conda/lib/python3.10/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/opt/conda/lib/python3.10/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/conda/lib/python3.10/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/typer/main.py", line 683, in wrapper
    return callback(**use_params)  # type: ignore
  File "/opt/conda/lib/python3.10/site-packages/text_generation_server/cli.py", line 89, in serve
    server.serve(
  File "/opt/conda/lib/python3.10/site-packages/text_generation_server/server.py", line 215, in serve
    asyncio.run(
  File "/opt/conda/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/opt/conda/lib/python3.10/asyncio/base_events.py", line 636, in run_until_complete
    self.run_forever()
  File "/opt/conda/lib/python3.10/asyncio/base_events.py", line 603, in run_forever
    self._run_once()
  File "/opt/conda/lib/python3.10/asyncio/base_events.py", line 1909, in _run_once
    handle._run()
  File "/opt/conda/lib/python3.10/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
> File "/opt/conda/lib/python3.10/site-packages/text_generation_server/server.py", line 161, in serve_inner
    model = get_model(
  File "/opt/conda/lib/python3.10/site-packages/text_generation_server/models/__init__.py", line 310, in get_model
    return FlashMixtral(
  File "/opt/conda/lib/python3.10/site-packages/text_generation_server/models/flash_mixtral.py", line 21, in __init__
    super(FlashMixtral, self).__init__(
  File "/opt/conda/lib/python3.10/site-packages/text_generation_server/models/flash_mistral.py", line 318, in __init__
    SLIDING_WINDOW_BLOCKS = math.ceil(config.sliding_window / BLOCK_SIZE)
TypeError: unsupported operand type(s) for /: 'NoneType' and 'int'

2023-12-20T12:34:18.542525Z ERROR text_generation_launcher: Error when initializing model
Traceback (most recent call last):
  File "/opt/conda/bin/text-generation-server", line 8, in <module>
    sys.exit(app())
  File "/opt/conda/lib/python3.10/site-packages/typer/main.py", line 311, in __call__
    return get_command(self)(*args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/typer/core.py", line 778, in main
    return _main(
  File "/opt/conda/lib/python3.10/site-packages/typer/core.py", line 216, in _main
    rv = self.invoke(ctx)
  File "/opt/conda/lib/python3.10/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/opt/conda/lib/python3.10/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/conda/lib/python3.10/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/typer/main.py", line 683, in wrapper
    return callback(**use_params)  # type: ignore
  File "/opt/conda/lib/python3.10/site-packages/text_generation_server/cli.py", line 89, in serve
    server.serve(
  File "/opt/conda/lib/python3.10/site-packages/text_generation_server/server.py", line 215, in serve
    asyncio.run(
  File "/opt/conda/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/opt/conda/lib/python3.10/asyncio/base_events.py", line 636, in run_until_complete
    self.run_forever()
  File "/opt/conda/lib/python3.10/asyncio/base_events.py", line 603, in run_forever
    self._run_once()
  File "/opt/conda/lib/python3.10/asyncio/base_events.py", line 1909, in _run_once
    handle._run()
  File "/opt/conda/lib/python3.10/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
> File "/opt/conda/lib/python3.10/site-packages/text_generation_server/server.py", line 161, in serve_inner
    model = get_model(
  File "/opt/conda/lib/python3.10/site-packages/text_generation_server/models/__init__.py", line 310, in get_model
    return FlashMixtral(
  File "/opt/conda/lib/python3.10/site-packages/text_generation_server/models/flash_mixtral.py", line 21, in __init__
    super(FlashMixtral, self).__init__(
  File "/opt/conda/lib/python3.10/site-packages/text_generation_server/models/flash_mistral.py", line 318, in __init__
    SLIDING_WINDOW_BLOCKS = math.ceil(config.sliding_window / BLOCK_SIZE)
TypeError: unsupported operand type(s) for /: 'NoneType' and 'int'

2023-12-20T12:34:19.909381Z  INFO shard-manager: text_generation_launcher: Waiting for shard to be ready... rank=1
2023-12-20T12:34:19.909411Z  INFO shard-manager: text_generation_launcher: Waiting for shard to be ready... rank=0
2023-12-20T12:34:19.909390Z  INFO shard-manager: text_generation_launcher: Waiting for shard to be ready... rank=3
2023-12-20T12:34:19.909394Z  INFO shard-manager: text_generation_launcher: Waiting for shard to be ready... rank=2
2023-12-20T12:34:20.412017Z ERROR shard-manager: text_generation_launcher: Shard complete standard error output:

╭───────────────────── Traceback (most recent call last) ──────────────────────╮
│ /opt/conda/lib/python3.10/site-packages/text_generation_server/cli.py:89 in  │
│ serve                                                                        │
│                                                                              │
│    86 │   │   raise RuntimeError(                                            │
│    87 │   │   │   "Only 1 can be set between `dtype` and `quantize`, as they │
│    88 │   │   )                                                              │
│ ❱  89 │   server.serve(                                                      │
│    90 │   │   model_id,                                                      │
│    91 │   │   revision,                                                      │
│    92 │   │   sharded,                                                       │
│                                                                              │
│ /opt/conda/lib/python3.10/site-packages/text_generation_server/server.py:215 │
│ in serve                                                                     │
│                                                                              │
│   212 │   │   │   logger.info("Signal received. Shutting down")              │
│   213 │   │   │   await server.stop(0)                                       │
│   214 │                                                                      │
│ ❱ 215 │   asyncio.run(                                                       │
│   216 │   │   serve_inner(                                                   │
│   217 │   │   │   model_id, revision, sharded, quantize, speculate, dtype, t │
│   218 │   │   )                                                              │
│                                                                              │
│ /opt/conda/lib/python3.10/asyncio/runners.py:44 in run                       │
│                                                                              │
│   41 │   │   events.set_event_loop(loop)                                     │
│   42 │   │   if debug is not None:                                           │
│   43 │   │   │   loop.set_debug(debug)                                       │
│ ❱ 44 │   │   return loop.run_until_complete(main)                            │
│   45 │   finally:                                                            │
│   46 │   │   try:                                                            │
│   47 │   │   │   _cancel_all_tasks(loop)                                     │
│                                                                              │
│ /opt/conda/lib/python3.10/asyncio/base_events.py:649 in run_until_complete   │
│                                                                              │
│    646 │   │   if not future.done():                                         │
│    647 │   │   │   raise RuntimeError('Event loop stopped before Future comp │
│    648 │   │                                                                 │
│ ❱  649 │   │   return future.result()                                        │
│    650 │                                                                     │
│    651 │   def stop(self):                                                   │
│    652 │   │   """Stop running the event loop.                               │
│                                                                              │
│ /opt/conda/lib/python3.10/site-packages/text_generation_server/server.py:161 │
│ in serve_inner                                                               │
│                                                                              │
│   158 │   │   │   server_urls = [local_url]                                  │
│   159 │   │                                                                  │
│   160 │   │   try:                                                           │
│ ❱ 161 │   │   │   model = get_model(                                         │
│   162 │   │   │   │   model_id,                                              │
│   163 │   │   │   │   revision,                                              │
│   164 │   │   │   │   sharded,                                               │
│                                                                              │
│ /opt/conda/lib/python3.10/site-packages/text_generation_server/models/__init │
│ __.py:310 in get_model                                                       │
│                                                                              │
│   307 │                                                                      │
│   308 │   if model_type == "mixtral":                                        │
│   309 │   │   if MIXTRAL:                                                    │
│ ❱ 310 │   │   │   return FlashMixtral(                                       │
│   311 │   │   │   │   model_id,                                              │
│   312 │   │   │   │   revision,                                              │
│   313 │   │   │   │   quantize=quantize,                                     │
│                                                                              │
│ /opt/conda/lib/python3.10/site-packages/text_generation_server/models/flash_ │
│ mixtral.py:21 in __init__                                                    │
│                                                                              │
│   18 │   │   dtype: Optional[torch.dtype] = None,                            │
│   19 │   │   trust_remote_code: bool = False,                                │
│   20 │   ):                                                                  │
│ ❱ 21 │   │   super(FlashMixtral, self).__init__(                             │
│   22 │   │   │   config_cls=MixtralConfig,                                   │
│   23 │   │   │   model_cls=FlashMixtralForCausalLM,                          │
│   24 │   │   │   model_id=model_id,                                          │
│                                                                              │
│ /opt/conda/lib/python3.10/site-packages/text_generation_server/models/flash_ │
│ mistral.py:318 in __init__                                                   │
│                                                                              │
│   315 │   │                                                                  │
│   316 │   │   # Set context windows                                          │
│   317 │   │   SLIDING_WINDOW = config.sliding_window                         │
│ ❱ 318 │   │   SLIDING_WINDOW_BLOCKS = math.ceil(config.sliding_window / BLOC │
│   319 │   │                                                                  │
│   320 │   │   torch.distributed.barrier(group=self.process_group)            │
│   321                                                                        │
╰──────────────────────────────────────────────────────────────────────────────╯
TypeError: unsupported operand type(s) for /: 'NoneType' and 'int' rank=0
2023-12-20T12:34:20.460680Z ERROR text_generation_launcher: Shard 0 failed to start
2023-12-20T12:34:20.460780Z  INFO text_generation_launcher: Shutting down shards
2023-12-20T12:34:20.513445Z ERROR shard-manager: text_generation_launcher: Shard complete standard error output:

╭───────────────────── Traceback (most recent call last) ──────────────────────╮
│ /opt/conda/lib/python3.10/site-packages/text_generation_server/cli.py:89 in  │
│ serve                                                                        │
│                                                                              │
│    86 │   │   raise RuntimeError(                                            │
│    87 │   │   │   "Only 1 can be set between `dtype` and `quantize`, as they │
│    88 │   │   )                                                              │
│ ❱  89 │   server.serve(                                                      │
│    90 │   │   model_id,                                                      │
│    91 │   │   revision,                                                      │
│    92 │   │   sharded,                                                       │
│                                                                              │
│ /opt/conda/lib/python3.10/site-packages/text_generation_server/server.py:215 │
│ in serve                                                                     │
│                                                                              │
│   212 │   │   │   logger.info("Signal received. Shutting down")              │
│   213 │   │   │   await server.stop(0)                                       │
│   214 │                                                                      │
│ ❱ 215 │   asyncio.run(                                                       │
│   216 │   │   serve_inner(                                                   │
│   217 │   │   │   model_id, revision, sharded, quantize, speculate, dtype, t │
│   218 │   │   )                                                              │
│                                                                              │
│ /opt/conda/lib/python3.10/asyncio/runners.py:44 in run                       │
│                                                                              │
│   41 │   │   events.set_event_loop(loop)                                     │
│   42 │   │   if debug is not None:                                           │
│   43 │   │   │   loop.set_debug(debug)                                       │
│ ❱ 44 │   │   return loop.run_until_complete(main)                            │
│   45 │   finally:                                                            │
│   46 │   │   try:                                                            │
│   47 │   │   │   _cancel_all_tasks(loop)                                     │
│                                                                              │
│ /opt/conda/lib/python3.10/asyncio/base_events.py:649 in run_until_complete   │
│                                                                              │
│    646 │   │   if not future.done():                                         │
│    647 │   │   │   raise RuntimeError('Event loop stopped before Future comp │
│    648 │   │                                                                 │
│ ❱  649 │   │   return future.result()                                        │
│    650 │                                                                     │
│    651 │   def stop(self):                                                   │
│    652 │   │   """Stop running the event loop.                               │
│                                                                              │
│ /opt/conda/lib/python3.10/site-packages/text_generation_server/server.py:161 │
│ in serve_inner                                                               │
│                                                                              │
│   158 │   │   │   server_urls = [local_url]                                  │
│   159 │   │                                                                  │
│   160 │   │   try:                                                           │
│ ❱ 161 │   │   │   model = get_model(                                         │
│   162 │   │   │   │   model_id,                                              │
│   163 │   │   │   │   revision,                                              │
│   164 │   │   │   │   sharded,                                               │
│                                                                              │
│ /opt/conda/lib/python3.10/site-packages/text_generation_server/models/__init │
│ __.py:310 in get_model                                                       │
│                                                                              │
│   307 │                                                                      │
│   308 │   if model_type == "mixtral":                                        │
│   309 │   │   if MIXTRAL:                                                    │
│ ❱ 310 │   │   │   return FlashMixtral(                                       │
│   311 │   │   │   │   model_id,                                              │
│   312 │   │   │   │   revision,                                              │
│   313 │   │   │   │   quantize=quantize,                                     │
│                                                                              │
│ /opt/conda/lib/python3.10/site-packages/text_generation_server/models/flash_ │
│ mixtral.py:21 in __init__                                                    │
│                                                                              │
│   18 │   │   dtype: Optional[torch.dtype] = None,                            │
│   19 │   │   trust_remote_code: bool = False,                                │
│   20 │   ):                                                                  │
│ ❱ 21 │   │   super(FlashMixtral, self).__init__(                             │
│   22 │   │   │   config_cls=MixtralConfig,                                   │
│   23 │   │   │   model_cls=FlashMixtralForCausalLM,                          │
│   24 │   │   │   model_id=model_id,                                          │
│                                                                              │
│ /opt/conda/lib/python3.10/site-packages/text_generation_server/models/flash_ │
│ mistral.py:318 in __init__                                                   │
│                                                                              │
│   315 │   │                                                                  │
│   316 │   │   # Set context windows                                          │
│   317 │   │   SLIDING_WINDOW = config.sliding_window                         │
│ ❱ 318 │   │   SLIDING_WINDOW_BLOCKS = math.ceil(config.sliding_window / BLOC │
│   319 │   │                                                                  │
│   320 │   │   torch.distributed.barrier(group=self.process_group)            │
│   321                                                                        │
╰──────────────────────────────────────────────────────────────────────────────╯
TypeError: unsupported operand type(s) for /: 'NoneType' and 'int' rank=3
`

**Comment by amkazan** [comment]
also have errors in "06_gpu_and_ml / tgi_mixtral.py"

but for me it's somewhere here I think:
155 │   print(                                                               │
│ ❱ 156 │   │   Model().generate.remote(                                         │
│   157 │   │   │   "Implement a Python function to compute the Fibonacci number

**Comment by thundergolfer** [comment]
closed by #533
