### ISSUE TITLE
Run ComfyUI Example Not Working 

### ISSUE THREAD

**Issue by hongil0316** [modal-labs/modal-examples#607]
Hi team, I'm following this tutorial to run ComfyUI on modal. I was able to successfully launch the ComfyUI but QueuePrompt was returning this error: 

```
ERROR:root:Traceback (most recent call last):
  File "/root/execution.py", line 154, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/execution.py", line 84, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/execution.py", line 77, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/nodes.py", line 476, in load_checkpoint
    out = comfy.sd.load_checkpoint_guess_config(ckpt_path, output_vae=True, output_clip=True, embedding_directory=folder_paths.get_folder_paths("embeddings"))
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/comfy/sd.py", line 434, in load_checkpoint_guess_config
    sd = comfy.utils.load_torch_file(ckpt_path)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/comfy/utils.py", line 13, in load_torch_file
    sd = safetensors.torch.load_file(ckpt, device=device.type)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/safetensors/torch.py", line 308, in load_file
    with safe_open(filename, framework="pt", device=device) as f:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
safetensors_rust.SafetensorError: Error while deserializing header: HeaderTooLarge
```

* **Tutorial**: https://modal.com/docs/examples/comfy_ui?utm_medium=email&_hsmi=293816638&utm_content=293816638&utm_source=hs_email
* **app**: https://modal.com/hongil0316/logs/ap-AItnfOrUo95aJ8gfUitasR

I was expecting the example to succeed if I don't make any changes to it but I wasn't able to generate any image with the current tutorial. Any help would be appreciated.

**Comment by hongil0316** [comment]
I stopped the application for now but you should be able to find the logs here: https://modal.com/hongil0316/logs/ap-AItnfOrUo95aJ8gfUitasR. Not too sure if you have the access.

**Comment by kning** [comment]
are you running the default workflow? im not able to reproduce though sometimes the container does spin down after inactivity try refreshing and queueing again?

**Comment by kning** [comment]
make sense, thanks for following up!
