### ISSUE TITLE
Deplopy code agents with langserve/langgraph

### ISSUE THREAD

**Issue by LNshuti** [modal-labs/modal-examples#664]
Hi! I have set the modal client secrets using the **.modal.toml** file under /codelangchain with defined *token_id and token_secret*

When I run **modal serve .\app.py**, I get the following error: **Stopping app - uncaught exception raised locally: NotFoundError('Could not find secret').**

How do I ensure that the application recognizes the defined authentication tokens?

```````````````````````````````````````````````
unhandled exception during asyncio.run() shutdown
task: <Task finished name='Task-28' coro=<Resolver.load.<locals>.loader() done, defined at C:\Users\LNshuti\AppData\Local\miniconda3\envs\modal-deploy\Lib\site-packages\modal\_resolver.py:123> exception=RuntimeError('cannot schedule new futures after shutdown')>
Traceback (most recent call last):
  File "C:\Users\LNshuti\AppData\Local\miniconda3\envs\modal-deploy\Lib\site-packages\modal\_resolver.py", line 154, in load
    return await cached_future
     
  File "C:\Users\LNshuti\AppData\Local\miniconda3\envs\modal-deploy\Lib\site-packages\modal\_resolver.py", line 130, in loader
    await obj._load(obj, self, existing_object_id)
  File "C:\Users\LNshuti\AppData\Local\miniconda3\envs\modal-deploy\Lib\site-packages\modal\mount.py", line 500, in _load_mount
    resp = await retry_transient_errors(resolver.client.stub.MountGetOrCreate, req, base_delay=1)
           
  File "C:\Users\LNshuti\AppData\Local\miniconda3\envs\modal-deploy\Lib\site-packages\modal\_utils\grpc_utils.py", line 249, in retry_transient_errors
    return await fn(*args, metadata=metadata, timeout=timeout)
       
  File "C:\Users\LNshuti\AppData\Local\miniconda3\envs\modal-deploy\Lib\site-packages\grpclib\client.py", line 903, in __call__
    await stream.send_message(message, end=True)
  File "C:\Users\LNshuti\AppData\Local\miniconda3\envs\modal-deploy\Lib\site-packages\grpclib\client.py", line 241, in send_message
    await self.send_request()
  File "C:\Users\LNshuti\AppData\Local\miniconda3\envs\modal-deploy\Lib\site-packages\grpclib\client.py", line 173, in send_request
    protocol = await self._channel.__connect__()
               
  File "C:\Users\LNshuti\AppData\Local\miniconda3\envs\modal-deploy\Lib\site-packages\modal\_utils\grpc_utils.py", line 114, in __connect__
    protocol = await self._create_connection()
               
  File "C:\Users\LNshuti\AppData\Local\miniconda3\envs\modal-deploy\Lib\site-packages\grpclib\client.py", line 725, in _create_connection
    _, protocol = await self._loop.create_connection(
                    File "C:\Users\LNshuti\AppData\Local\miniconda3\envs\modal-deploy\Lib\asyncio\base_events.py", line 1045, in create_connection
    infos = await self._ensure_resolved(
            
  File "C:\Users\LNshuti\AppData\Local\miniconda3\envs\modal-deploy\Lib\asyncio\base_events.py", line 1419, in _ensure_resolved
    return await loop.getaddrinfo(host, port, family=family, type=type,
           
  File "C:\Users\LNshuti\AppData\Local\miniconda3\envs\modal-deploy\Lib\asyncio\base_events.py", line 867, in getaddrinfo
    return await self.run_in_executor(
                 
  File "C:\Users\LNshuti\AppData\Local\miniconda3\envs\modal-deploy\Lib\asyncio\base_events.py", line 829, in run_in_executor
    executor.submit(func, *args), loop=self)
    
  File "C:\Users\LNshuti\AppData\Local\miniconda3\envs\modal-deploy\Lib\concurrent\futures\thread.py", line 167, in submit
    raise RuntimeError('cannot schedule new futures after shutdown')
RuntimeError: cannot schedule new futures after shutdown
unhandled exception during asyncio.run() shutdown
task: <Task finished name='Task-16' coro=<Resolver.load() done, defined at C:\Users\LNshuti\AppData\Local\miniconda3\envs\modal-deploy\Lib\site-packages\modal\_resolver.py:94> exception=RuntimeError('cannot schedule new futures after shutdown')>
Traceback (most recent call last):
  File "C:\Users\LNshuti\AppData\Local\miniconda3\envs\modal-deploy\Lib\site-packages\modal\_resolver.py", line 154, in load
    return await cached_future
           
  File "C:\Users\LNshuti\AppData\Local\miniconda3\envs\modal-deploy\Lib\site-packages\modal\_resolver.py", line 130, in loader
    await obj._load(obj, self, existing_object_id)
  File "C:\Users\LNshuti\AppData\Local\miniconda3\envs\modal-deploy\Lib\site-packages\modal\mount.py", line 500, in _load_mount
    resp = await retry_transient_errors(resolver.client.stub.MountGetOrCreate, req, base_delay=1)
           
  File "C:\Users\LNshuti\AppData\Local\miniconda3\envs\modal-deploy\Lib\site-packages\modal\_utils\grpc_utils.py", line 249, in retry_transient_errors
    return await fn(*args, metadata=metadata, timeout=timeout)
           
  File "C:\Users\LNshuti\AppData\Local\miniconda3\envs\modal-deploy\Lib\site-packages\grpclib\client.py", line 903, in __call__
    await stream.send_message(message, end=True)
  File "C:\Users\LNshuti\AppData\Local\miniconda3\envs\modal-deploy\Lib\site-packages\grpclib\client.py", line 241, in send_message
    await self.send_request()
  File "C:\Users\LNshuti\AppData\Local\miniconda3\envs\modal-deploy\Lib\site-packages\grpclib\client.py", line 173, in send_request
    protocol = await self._channel.__connect__()
(modal-deploy) PS C:\Users\LNshuti\OneDrive - Sony\Desktop\learn\modal-examples\06_gpu_and_ml\langchains\codelangchain> modal serve .\app.py
```````````````````````````````````````````````

**Comment by charlesfrye** [comment]
Hey there!

The error isn't because of missing secrets for accessing the Modal service but instead because you don't have the various `modal.Secret`s set up -- these are the secrets you need to access other services besides Modal, things like API keys, database passwords, etc. I believe this example uses the following secrets: a langsmith API key and an OpenAI API key, named `my-openai-secret` and `my-langsmith-secret`, respectively. 

That's on us -- this example is pretty poorly documented, because we just put it out recently and haven't written up the explanations. Sorry about that!

You can read more about how to set up Modal Secrets in [our guide](https://modal.com/docs/guide/secrets#secrets).
