### ISSUE TITLE
"RuntimeError: No HIP GPUs are available" 

### ISSUE THREAD

**Issue by 6174** [modal-labs/modal-examples#681]
Follow the [example of ComfyUI](https://modal.com/docs/examples/comfy_ui#run-comfyui) in modal , show error RuntimeError: No HIP GPUs are available, the original gpu type is any, I changed it to Nvidia T4, but the same error shows

the code 

```py
import modal
import pathlib
import subprocess

CHECKPOINTS = [
	"https://huggingface.co/stabilityai/stable-diffusion-2-inpainting/resolve/main/512-inpainting-ema.ckpt"
]

def download_checkpoints():
	import httpx
	from tqdm import tqdm

	for url in CHECKPOINTS:
		checkpoints_directory = "/comfyui/models/checkpoints"
		local_filename = url.split("/")[-1]
		local_filepath = pathlib.Path(checkpoints_directory, local_filename)
		local_filepath.parent.mkdir(parents=True, exist_ok=True)

		print(f"downloading {url} ...")
		with httpx.stream("GET", url, follow_redirects=True) as stream:
			total = int(stream.headers["Content-Length"])
			with open(local_filepath, "wb") as f, tqdm(
				total=total, unit_scale=True, unit_divisor=1024, unit="B"
			) as progress:
				num_bytes_downloaded = stream.num_bytes_downloaded
				for data in stream.iter_bytes():
					f.write(data)
					progress.update(
							stream.num_bytes_downloaded - num_bytes_downloaded
					)
					num_bytes_downloaded = stream.num_bytes_downloaded

PLUGINS = [
	{
		"url": "https://github.com/coreyryanhanson/ComfyQR",
		"requirements": "requirements.txt",
	}
]

def download_plugins():
	import subprocess

	for plugin in PLUGINS:
		url = plugin["url"]
		name = url.split("/")[-1]
		command = f"cd /comfyui/custom_nodes && git clone {url}"
		try:
			subprocess.run(command, shell=True, check=True)
			print(f"Repository {url} cloned successfully")
		except subprocess.CalledProcessError as e:
			print(f"Error cloning repository: {e.stderr}")
		if plugin.get("requirements"):
			pip_command = f"cd /comfyui/custom_nodes/{name} && pip install -r {plugin['requirements']}"
		try:
			subprocess.run(pip_command, shell=True, check=True)
			print(f"Requirements for {url} installed successfully")
		except subprocess.CalledProcessError as e:
			print(f"Error installing requirements: {e.stderr}")

comfyui_commit_sha = "a38b9b3ac152fb5679dad03813a93c09e0a4d15e"


image = (
	modal.Image.debian_slim(python_version="3.11")
	.apt_install("git")
	# Here we place the latest ComfyUI repository code into /comfyui.
	# Because /comfyui is almost empty, but not entirely empty
	# as it contains this comfy_ui.py script, `git clone` won't work.
	# As a workaround we `init` inside the non-empty directory, then `checkout`.
	.run_commands(
		"mkdir /comfyui && cd /comfyui && git init .",
		"cd /comfyui && git remote add --fetch origin https://github.com/comfyanonymous/ComfyUI",
		f"cd /comfyui && git checkout master",
		"cd /comfyui && pip install --pre torch torchvision torchaudio --index-url https://download.pytorch.org/whl/nightly/rocm6.0",
		"cd /comfyui && pip install -r requirements.txt --extra-index-url https://download.pytorch.org/whl/cu121",
		"cd /comfyui && git clone https://github.com/pydn/ComfyUI-to-Python-Extension.git",
		"cd /comfyui/ComfyUI-to-Python-Extension && pip install -r requirements.txt",
	)
	.pip_install(
		"httpx",
		"requests",
		"tqdm",
	)
	.run_function(download_checkpoints)
	.run_function(download_plugins)
)

stub = modal.Stub("example-comfyui", image=image)

@stub.function(
	gpu="Nvidia T4",
	# Allows 100 concurrent requests per container.
	allow_concurrent_inputs=100,
	# Restrict to 1 container because we want our ComfyUI session state
	# to be on a single container.
	concurrency_limit=1,
	keep_warm=1,
	timeout=1800,
)
@modal.web_server(8188, startup_timeout=30)
def web():
	cmd = "cd /comfyui && python main.py --dont-print-server --multi-user --listen --port 8188"
	subprocess.Popen(cmd, shell=True)
```

the error:

```
Traceback (most recent call last):
Runner failed with exception: TimeoutError('Waited too long for port 8188 to start accepting connections. Make sure the web server is listening on all interfaces, or adjust `startup_timeout`.')
  File "/pkg/modal/_asgi.py", line 190, in wait_for_web_server
    with socket.create_connection((host, port), timeout=timeout):
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/socket.py", line 850, in create_connection
    raise exceptions[0]
  File "/usr/local/lib/python3.11/socket.py", line 835, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/pkg/modal/_container_entrypoint.py", line 488, in handle_user_exception
    yield
  File "/pkg/modal/_container_entrypoint.py", line 1006, in main
    imp_fun = import_function(
              ^^^^^^^^^^^^^^^^
  File "/pkg/modal/_container_entrypoint.py", line 951, in import_function
    wait_for_web_server(host, port, timeout=startup_timeout)
  File "/pkg/modal/_asgi.py", line 195, in wait_for_web_server
    raise TimeoutError(
TimeoutError: Waited too long for port 8188 to start accepting connections. Make sure the web server is listening on all interfaces, or adjust `startup_timeout`.
Traceback (most recent call last):
  File "/comfyui/main.py", line 76, in <module>
    import execution
  File "/comfyui/execution.py", line 11, in <module>
    import nodes
  File "/comfyui/nodes.py", line 21, in <module>
    import comfy.diffusers_load
  File "/comfyui/comfy/diffusers_load.py", line 3, in <module>
    import comfy.sd
  File "/comfyui/comfy/sd.py", line 5, in <module>
    from comfy import model_management
  File "/comfyui/comfy/model_management.py", line 119, in <module>
    total_vram = get_total_memory(get_torch_device()) / (1024 * 1024)
                                  ^^^^^^^^^^^^^^^^^^
  File "/comfyui/comfy/model_management.py", line 88, in get_torch_device
    return torch.device(torch.cuda.current_device())
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/torch/cuda/__init__.py", line 789, in current_device
    _lazy_init()
  File "/usr/local/lib/python3.11/site-packages/torch/cuda/__init__.py", line 293, in _lazy_init
    torch._C._cuda_init()
RuntimeError: No HIP GPUs are available
```

**Comment by luiscape** [comment]
Hi @6174, the issue is here:

```
	gpu="Nvidia T4",
```
this needs to be `gpu="t4"` or `gpu=modal.gpu.T4()`.

**Comment by 6174** [comment]
@luiscape  Thanks for reply, I tried change the gpu to  t4 and modal.gpu.T4, but the same error showed

**Comment by Inferencer** [comment]
> I found the error is in build image process "cd /comfyui && pip install --pre torch torchvision torchaudio --index-url https://download.pytorch.org/whl/nightly/rocm6.0"

did you fix this? having a similar issue on another repo

**Comment by charlesfrye** [comment]
it looks like you are trying to install a version of PyTorch compiled for AMD (`rocm`), leading to an error message indicating that no compatible GPUs are available (`No HIP GPUs`).
