### ISSUE TITLE
Comfy example not working anymore

### ISSUE THREAD

**Issue by madriss** [modal-labs/modal-examples#801]
Hello everyone,

I was trying to get the comfyui example working on modal. However I am getting a weird behaviour :

I run the following commands : 

1. in a terminal I run : **modal serve comfyapp.py**
2. in a second terminal I run : python3 comfyclient.py --dev --modal-workspace myworkspace--prompt "a white heron"

However as I see the logs in the first terminal, eveerything seems to be doubled (or run twice) and I get a weird error regarding the creation of /root/user/
It will also print continuously : Server still standing up...

Complete message below : 

`Total VRAM 15095 MB, total RAM 347440 MB
Total VRAM 15095 MB, total RAM 347440 MB
xformers version: 0.0.26.post1
xformers version: 0.0.26.post1
Set vram state to: NORMAL_VRAM
Device: cuda:0 Tesla T4 : cudaMallocAsync
VAE dtype: torch.float32
Set vram state to: NORMAL_VRAM
Device: cuda:0 Tesla T4 : cudaMallocAsync
VAE dtype: torch.float32
Using xformers cross attention
Using xformers cross attention
Traceback (most recent call last):
  File "/root/main.py", line 206, in <module>
    server = server.PromptServer(loop)
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/server.py", line 71, in __init__
    self.user_manager = UserManager()
                        ^^^^^^^^^^^^^
  File "/root/app/user_manager.py", line 20, in __init__
    os.mkdir(user_directory)
FileExistsError: [Errno 17] File exists: '/root/user'

Import times for custom nodes:
   0.0 seconds: /root/custom_nodes/websocket_image_save.py
   0.0 seconds: /root/custom_nodes/image-resize-comfyui

downloading https://raw.githubusercontent.com/comfyanonymous/ComfyUI_examples/master/inpaint/yosemite_inpaint_example.png ... to /root/input
100%|██████████| 1.41M/1.41M [00:00<00:00, 189MB/s]
Server still standing up...
Server still standing up...
Server still standing up...
Server still standing up...
Server still standing up...
Server still standing up...
`

Also, the link to the UI is working correctly. 

Here is my version of modal : 0.63.28

Thanks for your help !

**Comment by madriss** [comment]
If someone runs into the same issue just checkout to the commit : d33e74e6990f6f55c0bcb74e6decabfcd0b0a205 
and it will get fixed
