### ISSUE TITLE
Error no file named pytorch_lora_weights.bin found in directory /model

### ISSUE THREAD

**Issue by hoangmnsd** [modal-labs/modal-examples#854]
Hello,

I am facing this error when serving example [Dreambooth app](https://github.com/modal-labs/modal-examples/blob/main/06_gpu_and_ml/dreambooth/dreambooth_app.py). 

Full log here:

```
$ modal serve dreambooth_app.py
✓ Initialized. View run at https://modal.com/apps/USERNAME/main/ap-X
✓ Created objects.
├── 🔨 Created mount /home/USERNAME/dreambooth-modal/dreambooth_app.py
├── 🔨 Created mount /home/USERNAME/dreambooth-modal/assets
├── 🔨 Created function download_models.
├── 🔨 Created function train.
├── 🔨 Created function Model.*.
├── 🔨 Created web function fastapi_app => https://USERNAME--example-dreambooth-flux-fastapi-app-dev.modal.run
└── 🔨 Created function Model.inference.
️️⚡️ Serving... hit Ctrl-C to stop!
├── Watching /home/USERNAME/dreambooth-modal/assets.
└── Watching /home/USERNAME/dreambooth-modal.
    GET / -> 200 OK  (duration: 5.61 s, execution: 116.6 ms)
IMPORTANT: You are using gradio version 3.50.2, however version 4.29.0 is available, please upgrade.
--------
    GET /assets/index-a959df42.js -> 200 OK  (duration: 114.0 ms, execution: 60.9 ms)
    GET /assets/index-5ac12191.css -> 200 OK  (duration: 77.6 ms, execution: 13.5 ms)
    GET /info -> 200 OK  (duration: 399.6 ms, execution: 15.7 ms)
    GET /theme.css -> 200 OK  (duration: 71.2 ms, execution: 18.9 ms)
    GET /assets/Button-fb0eed2f.js -> 200 OK  (duration: 119.7 ms, execution: 27.6 ms)
    GET /assets/Blocks-14eb0294.js -> 200 OK  (duration: 175.8 ms, execution: 32.0 ms)
    GET /assets/Button-dd3ccceb.css -> 200 OK  (duration: 86.2 ms, execution: 14.5 ms)
    GET /assets/Blocks-0733f3b3.css -> 200 OK  (duration: 115.1 ms, execution: 16.1 ms)
    GET /assets/utils-c3e3db58.js -> 200 OK  (duration: 65.5 ms, execution: 15.7 ms)
    GET /assets/index-a5fdef40.js -> 200 OK  (duration: 113.3 ms, execution: 30.9 ms)
    GET /assets/StaticMarkdown-06312fb7.js -> 200 OK  (duration: 144.3 ms, execution: 37.6 ms)
    GET /assets/StaticMarkdown-1e08a987.css -> 200 OK  (duration: 61.0 ms, execution: 14.1 ms)
    GET /assets/index-93c91554.css -> 200 OK  (duration: 68.6 ms, execution: 12.8 ms)
    GET /assets/StaticForm-3812b7f1.css -> 200 OK  (duration: 98.6 ms, execution: 46.5 ms)
    GET /assets/Textbox-dde6f8cc.css -> 200 OK  (duration: 144.3 ms, execution: 18.3 ms)
    GET /assets/index-f62e764d.css -> 200 OK  (duration: 143.6 ms, execution: 31.1 ms)
    GET /assets/index-6bb91bb9.js -> 200 OK  (duration: 93.9 ms, execution: 21.0 ms)
    GET /assets/index-4594c4cd.js -> 200 OK  (duration: 113.8 ms, execution: 22.0 ms)
    GET /assets/StaticColumn-2853eb31.css -> 200 OK  (duration: 176.4 ms, execution: 27.7 ms)
    GET /assets/InteractiveTextbox-8c4d1407.js -> 200 OK  (duration: 59.9 ms, execution: 14.6 ms)
    GET /assets/BlockTitle-a5d1fe95.js -> 200 OK  (duration: 72.9 ms, execution: 13.5 ms)
    GET /assets/Textbox-8e45e7cb.js -> 200 OK  (duration: 152.4 ms, execution: 46.4 ms)
    GET /assets/Info-91922efa.js -> 200 OK  (duration: 65.6 ms, execution: 12.3 ms)
    GET /assets/Copy-76383fd2.js -> 200 OK  (duration: 66.0 ms, execution: 14.8 ms)
    GET /assets/index-da052169.js -> 200 OK  (duration: 70.6 ms, execution: 11.6 ms)
    GET /assets/BlockLabel-5f053d92.js -> 200 OK  (duration: 71.0 ms, execution: 12.6 ms)
    GET /assets/IconButton-a920ab53.js -> 200 OK  (duration: 67.5 ms, execution: 11.9 ms)
    GET /assets/Empty-3abf203a.js -> 200 OK  (duration: 75.6 ms, execution: 15.4 ms)
    GET /assets/ShareButton-cdf33464.js -> 200 OK  (duration: 114.5 ms, execution: 15.1 ms)
    GET /assets/Download-7d8a979b.js -> 200 OK  (duration: 111.4 ms, execution: 14.2 ms)
    GET /assets/Image-d002fc8a.js -> 200 OK  (duration: 75.4 ms, execution: 18.2 ms)
    GET /assets/utils-90f3612b.js -> 200 OK  (duration: 77.6 ms, execution: 22.5 ms)
    GET /assets/index-e5090eed.js -> 200 OK  (duration: 64.7 ms, execution: 13.7 ms)
    GET /assets/index-e75b4bc3.js -> 200 OK  (duration: 82.6 ms, execution: 12.8 ms)
    GET /assets/index-2c0d26e2.js -> 200 OK  (duration: 134.8 ms, execution: 11.5 ms)
    GET /assets/StaticColumn-e8db0143.js -> 200 OK  (duration: 78.4 ms, execution: 26.1 ms)
    GET /assets/logo-0a070fcf.svg -> 200 OK  (duration: 141.8 ms, execution: 13.3 ms)
    GET /assets/api-logo-5346f193.svg -> 200 OK  (duration: 422.7 ms, execution: 11.7 ms)
    GET /assets/StaticForm-0d359fd6.js -> 200 OK  (duration: 1.21 s, execution: 14.4 ms)
Loading pipeline components...:  57%|█████▋    | 4/7 [00:04<00:04,  1.64s/it]You set `add_prefix_space`. The tokenizer needs to be converted from the slow tokenizers
Loading pipeline components...:  86%|████████▌ | 6/7 [00:04<00:00,  1.21⠧ Running (0/2 containers active)... View app at https://modLoading checkpoint shards: 100%|██████████| 2/2 [00:01<00:00,  1.16it/s]
Loading pipeline components...: 100%|██████████| 7/7 [00:06<00:00,  1.08it/s]
Traceback (most recent call last):
  File "/pkg/modal/_container_io_manager.py", line 594, in handle_user_exception
    yield
  File "/pkg/modal/_container_entrypoint.py", line 668, in call_lifecycle_functions
    res = func(*args)
  File "/root/dreambooth_app.py", line 371, in load_model
    pipe.load_lora_weights(MODEL_DIR)
  File "/root/src/diffusers/loaders/lora_pipeline.py", line 1614, in load_lora_weights
    state_dict = self.lora_state_dict(pretrained_model_name_or_path_or_dict, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/huggingface_hub/utils/_validators.py", line 114, in _inner_fn
    return fn(*args, **kwargs)
  File "/root/src/diffusers/loaders/lora_pipeline.py", line 1565, in lora_state_dict
    state_dict = cls._fetch_state_dict(
  File "/root/src/diffusers/loaders/lora_base.py", line 295, in _fetch_state_dict
    model_file = _get_model_file(
  File "/usr/local/lib/python3.10/site-packages/huggingface_hub/utils/_validators.py", line 114, in _inner_fn
    return fn(*args, **kwargs)
  File "/root/src/diffusers/utils/hub_utils.py", line 310, in _get_model_file
    raise EnvironmentError(
OSError: Error no file named pytorch_lora_weights.bin found in directory /model.
Runner failed with exception: OSError('Error no file named pytorch_lora_weights.bin found in directory /model.')
Traceback (most recent call last):
```

Have anyone solve this? 
Thanks in advanced

**Comment by charlesfrye** [comment]
To serve or deploy that example, you need to first train the model with `modal run`.

**Comment by hoangmnsd** [comment]
> To serve or deploy that example, you need to first train the model with `modal run`.

yeah, I already run `modal run` command before. But it returned the same error:

```
$ modal run dreambooth_app.py
✓ Initialized. View run at https://modal.com/apps/USERNAME/main/ap-XXX
Building image im-pzG5D3jQsXbg

=> Step 0: FROM base

...

Saving image...
Image saved, took 57.70s
Finished image build for im-msiMiltKCwdG
✓ Created objects.
├── 🔨 Created mount /home/USERNAME/dreambooth-modal/dreambooth_app.py
├── 🔨 Created mount /home/USERNAME/dreambooth-modal/assets
├── 🔨 Created function download_models.
├── 🔨 Created function train.
├── 🔨 Created function Model.*.
├── 🔨 Created web function fastapi_app => https://USERNAME--example-dreambooth-flux-fastapi-app-dev.modal.run
└── 🔨 Created function Model.inference.
    GET / -> 200 OK  (duration: 11.9 s, execution: 515.4 ms)
IMPORTANT: You are using gradio version 3.50.2, however version 4.29.0 is available, please upgrade.
--------
    GET /assets/index-a959df42.js -> 200 OK  (duration: 1.01 s, execution: 782.2 ms)

...


3 images loaded
launching dreambooth training script
/usr/local/lib/python3.10/site-packages/accelerate/accelerator.py:399: UserWarning: `log_with=tensorboard` was passed but no supported trackers are currently installed.
  warnings.warn(f"`log_with={log_with}` was passed but no supported trackers are currently installed.")
Detected kernel version 4.4.0, which is below the recommended minimum of 5.5.0; this can cause the process to hang. It is recommended to upgrade the kernel to the minimum version or higher.
08/22/2024 15:31:50 - INFO - __main__ - Distributed environment: NO
Num processes: 1
Process index: 0
Local process index: 0
Device: cuda

Mixed precision type: bf16

You set `add_prefix_space`. The tokenizer needs to be converted from the slow tokenizers
/usr/local/lib/python3.10/site-packages/huggingface_hub/file_download.py:1150: FutureWarning: `resume_download` is deprecated and will be removed in version 1.0.0. Downloads always resume when possible. If you want to force a new download, use `force_download=True`.
  warnings.warn(
You are using a model of type clip_text_model to instantiate a model of type . This is not supported for all configurations of models and can yield errors.
You are using a model of type t5 to instantiate a model of type . This is not supported for all configurations of models and can yield errors.
Downloading shards:   0%|          | 0/2 [00:00<?, ?it/s]Downloading shards: 100%|██████████| 2/2 [00:00<00:00, 2525.93it/s]
Loading checkpoint shards:   0%|          | 0/2 [00:00<?, ?it/s]Loading checkpoint shards:  50%|█████     | 1/2 [00:04<00:04,  4.34s/it]Loading checkpoint shards: 100%|██████████| 2/2 [00:07<00:00,  3.57s/it]Loading checkpoint shards: 100%|██████████| 2/2 [00:07<00:00,  3.69s/it]
Fetching 3 files:   0%|          | 0/3 [00:00<?, ?it/s]Fetching 3 files: 100%|██████████| 3/3 [00:00<00:00, 49344.75it/s]
{'axes_dims_rope'} was not found in config. Values will be initialized to default values.
08/22/2024 15:32:27 - INFO - __main__ - ***** Running training *****
08/22/2024 15:32:27 - INFO - __main__ -   Num examples = 3
08/22/2024 15:32:27 - INFO - __main__ -   Num batches each epoch = 1
08/22/2024 15:32:27 - INFO - __main__ -   Num Epochs = 250
08/22/2024 15:32:27 - INFO - __main__ -   Instantaneous batch size per device = 3
08/22/2024 15:32:27 - INFO - __main__ -   Total train batch size (w. parallel, distributed & accumulation) = 3
08/22/2024 15:32:27 - INFO - __main__ -   Gradient Accumulation steps = 1
08/22/2024 15:32:27 - INFO - __main__ -   Total optimization steps = 250
Loading pipeline components...:  14%|█▍        | 1/7 [00:01<00:10,  1.79s/it]You set `add_prefix_space`. The tokenizer needs to be converted from the slow tokenizers
Loading checkpoint shards: 100%|██████████| 2/2 [00:06<00:00,  3.06s/it]s/it]
Loading pipeline components...: 100%|██████████| 7/7 [00:30<00:00,  4.39s/it]
Traceback (most recent call last):
Runner failed with exception: OSError('Error no file named pytorch_lora_weights.bin found in directory /model.')
  File "/pkg/modal/_container_io_manager.py", line 594, in handle_user_exception
    yield
  File "/pkg/modal/_container_entrypoint.py", line 668, in call_lifecycle_functions
    res = func(*args)
  File "/root/dreambooth_app.py", line 371, in load_model
    pipe.load_lora_weights(MODEL_DIR)
  File "/root/src/diffusers/loaders/lora_pipeline.py", line 1614, in load_lora_weights
    state_dict = self.lora_state_dict(pretrained_model_name_or_path_or_dict, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/huggingface_hub/utils/_validators.py", line 114, in _inner_fn
    return fn(*args, **kwargs)
  File "/root/src/diffusers/loaders/lora_pipeline.py", line 1565, in lora_state_dict
    state_dict = cls._fetch_state_dict(
  File "/root/src/diffusers/loaders/lora_base.py", line 295, in _fetch_state_dict
    model_file = _get_model_file(
  File "/usr/local/lib/python3.10/site-packages/huggingface_hub/utils/_validators.py", line 114, in _inner_fn
    return fn(*args, **kwargs)
  File "/root/src/diffusers/utils/hub_utils.py", line 310, in _get_model_file
    raise EnvironmentError(
OSError: Error no file named pytorch_lora_weights.bin found in directory /model.
```

**Comment by charlesfrye** [comment]
Interesting! Will take a look.

**Comment by charlesfrye** [comment]
@hoangmnsd I see this in the logs you shared:

> `GET /assets/index-a959df42.js -> 200 OK  (duration: 1.01 s, execution: 782.2 ms)`

Are you accessing the fastapi app at `https://USERNAME--example-dreambooth-flux-fastapi-app-dev.modal.run` before training has finished? That will indeed fail with the error message you reported, because the model hasn't been trained and saved. The `modal run` command needs to finish (and it takes a few minutes!) before you can access the application.

**Comment by charlesfrye** [comment]
The good news is that the error doesn't actually stop the training process, since it happens in the process running the web app, so if you allowed the run to complete, you should be able to `modal serve` or `modal deploy` the app and interact with it now.

**Comment by hoangmnsd** [comment]
> The good news is that the error doesn't actually stop the training process, since it happens in the process running the web app, so if you allowed the run to complete, you should be able to `modal serve` or `modal deploy` the app and interact with it now.

Thank you! you are right. I have to wait until `modal run` command finished.
