### ISSUE TITLE
Mochi Script not working

### ISSUE THREAD

**Issue by Curlypla** [modal-labs/modal-examples#999]
I use modal script with the default dataset, during preprocessing Step 1 works fine but during Step 2 I get errors in all the videos processed:

```
🎥 **Step 2: Run the VAE encoder on each video**
Timing load_encoder
Timing load_decoder
Stage                   Time(s)    Percent
load_encoder               1.12     28.88%
load_decoder               2.76     71.12%
Traceback (most recent call last)::00<00:05, 2.42it/s]
  File "/mochi/demos/fine_tuner/encode_videos.py", line 132, in batch_process
    preprocess(
  File "/mochi/demos/fine_tuner/encode_videos.py", line 65, in preprocess
    ldist.mean = cp_conv.gather_all_frames(ldist.mean)
  File "/mochi/src/genmo/mochi_preview/vae/cp_conv.py", line 67, in gather_all_frames
    cp_group = cp.get_cp_group()
  File "/mochi/src/genmo/mochi_preview/dit/joint_model/context_parallel.py", line 48, in get_cp_group
    raise RuntimeError("CP group not initialized")
RuntimeError: CP group not initialized00:29, 2.11s/it]
```

**Comment by charlesfrye** [comment]
Thanks for reporting! cc @erik-dunteman

**Comment by erik-dunteman** [comment]
On it

**Comment by erik-dunteman** [comment]
Moving discussion to https://github.com/genmoai/mochi/issues/98
